SRC_BASE_LIST	=	00.c 01.c 02.c 03.c 04.c 05.c 06.c 07.c 08.c 09.c 10.c
SRC_EXPAND_LST	=	11.c 12.c 13.c 14.c 15.c 16.c 17.c 18.c 19.c 20.c

# STRLEN
STRLEN_SRC_DIR	=	strlen/
STRLEN_SRC		=	${addprefix ${STRLEN_SRC_DIR}, ${SRC_BASE_LIST}}

# STRCPY
STRCPY_SRC_DIR	=	strcpy/
STRCPY_SRC		=	${addprefix ${STRCPY_SRC_DIR}, ${SRC_BASE_LIST}}

# STRCMP
STRCMP_SRC_DIR	=	strcmp/
STRCMP_SRC		=	${addprefix ${STRCMP_SRC_DIR}, ${SRC_BASE_LIST}}

# STRDUP
STRDUP_SRC_DIR	=	strdup/
STRDUP_SRC		=	${addprefix ${STRDUP_SRC_DIR}, ${SRC_BASE_LIST}}

# WRITE
WRITE_SRC_DIR	=	write/
WRITE_SRC_LST	=	${SRC_BASE_LIST} 11.c 12.c 13.c 14.c 15.c 16.c
WRITE_SRC		=	${addprefix ${WRITE_SRC_DIR}, ${WRITE_SRC_LST}}

# READ
READ_SRC_DIR	=	read/
READ_SRC		=	${addprefix ${READ_SRC_DIR}, ${SRC_BASE_LIST}}

# ATOI_BASE
ATOI_BASE_SRC_DIR	=	atoi_base/
ATOI_BASE_SRC_LST	=	${SRC_BASE_LIST} \
						${SRC_EXPAND_LST} \
						21.c 22.c 23.c 24.c 25.c 26.c 27.c 28.c 29.c \
						30.c 31.c 32.c 33.c 34.c 35.c 36.c 37.c 38.c 39.c \
						utils.c 
ATOI_BASE_SRC		=	${addprefix ${ATOI_BASE_SRC_DIR}, ${ATOI_BASE_SRC_LST}}

# LIST_SIZE
LIST_SIZE_SRC_DIR	=	lsit_size/
LIST_SIZE_SRC		=	${addprefix ${LIST_SIZE_SRC_DIR}, ${SRC_BASE_LIST}}

# LIST_SORT
LIST_SORT_SRC_DIR	=	list_front/
LIST_SORT_SRC		=	${addprefix ${LIST_SORT_SRC_DIR}, ${SRC_BASE_LIST}}

# LIST_REMOVE_IF
LIST_REMOVE_IF_SRC_DIR	=	list_remove_if/
LIST_REMOVE_IF_SRC_LST	=	${SRC_BASE_LIST}
LIST_REMOVE_IF_SRC		=	${addprefix ${LIST_REMOVE_IF_SRC_DIR}, ${LIST_REMOVE_IF_SRC_LST}}

# LIST_PUSH_FRONT
LIST_PUSH_FRONT_SRC_DIR	=	list_push_front/
LIST_PUSH_FRONT_SRC_LST	=	${SRC_BASE_LIST} utils.c
LIST_PUSH_FRONT_SRC		=	${addprefix ${LIST_PUSH_FRONT_SRC_DIR}, ${LIST_PUSH_FRONT_SRC_LST}}